# Generated by Django 5.0.7 on 2024-07-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='named_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='named_url'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='url'),
        ),
    ]
