# Generated by Django 5.0.7 on 2024-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
